name: Deploy Frontend

on:
  push:
    branches:
      - github-CI
      - azure-CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t mauro014/react-test -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true mauro014/react-test npm test

  deploy-azure:
    if: github.ref == 'refs/heads/azure-CI'
    runs-on: ubuntu-latest
    needs: build  # Ensure testing completes before deployment
    steps: 
      - uses: actions/checkout@v4

      - name: Azure Login # https://github.com/marketplace/actions/azure-container-registry-login
        uses: azure/docker-login@v2
        with: 
          login-server: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image to Azure Container Registry
        run: |
          docker build . -t ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/frontend:latest .
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/frontend:latest

