name: Deploy Frontend
on:
  push:
    branches:
      - github-CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t mauro014/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true mauro014/react-test npm test
