name: Deploy Frontend
on:
  push:
    branches:
      - github-CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ var.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t mauro014/react-test -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true mauro014/react-test npm test